### ISSUE TITLE
Can't get it to send notifiaction on print start/end etc

### ISSUE THREAD

**Issue by JediMongoose** [leafeven/sonicpad#1]
Hi. First, thanks for sharing your code. This is something I've been after for a while.

I've got your script installed and modifed my printer.cfg. The macro buttons show up in the Sonicpad Web GUI, and if I click on any of them it successfully sends a message.

But it doesn't send a message when the print actually starts or finishes - it's like I'm missing a step where I need to hook these macros into actual events?

Any help much appreciated :)

**Comment by leafeven** [comment]
@JediMongoose  my apologies, you are correct, my documentation skipped the very last step, include the PUSH_PRINT_X macros in the existing macros, I updated the readme and example printer.cfg, to include this step and show a quick example of the places my sonic pad is currently configured

**Comment by JediMongoose** [comment]
Great - thanks for your speedy reply :)

I've made the changes to printer.cfg... but it's still not sending notifications on start/stop etc :(

Here's my file - is this correct?:
```
# !Ender-5 S1
# printer_size: 220x220x280
# version: 3.6
# To use this config, during "make menuconfig" select the STM32F401
# with a "64KiB bootloader" and serial (on USART1 PA10/PA9)
# communication.

# Flash this firmware by copying "out/klipper.bin" to a SD card and
# turning on the printer with the card inserted. The firmware
# filename must end in ".bin" and must not match the last filename
# that was flashed.

# See docs/Config_Reference.md for a description of parameters.

###fluidd set
[include cx_printer.cfg]



[display_status]

[pause_resume]

[gcode_macro START_PRINT]
gcode:
  # your start printing macro
  PUSH_PRINT_START

[gcode_macro END_PRINT]
gcode:
  PUSH_PRINT_STOP
  # rest of your finish print macro

[gcode_macro PAUSE]
description: Pause the actual running print
rename_existing: PAUSE_BASE
# change this if you need more or less extrusion
variable_extrude: 1.0
gcode:
  ##### read E from pause macro #####
  {% set E = printer["gcode_macro PAUSE"].extrude|float %}
  ##### set park positon for x and y #####
  # default is your max posion from your printer.cfg
  {% set x_park = printer.toolhead.axis_maximum.x|float - 5.0 %}
  {% set y_park = printer.toolhead.axis_maximum.y|float - 5.0 %}
  ##### calculate save lift position #####
  {% set max_z = printer.toolhead.axis_maximum.z|float %}
  {% set act_z = printer.toolhead.position.z|float %}
  {% if act_z < (max_z - 2.0) %}
      {% set z_safe = 2.0 %}
  {% else %}
      {% set z_safe = max_z - act_z %}
  {% endif %}
  ##### end of definitions #####
  PAUSE_BASE
  G91
  {% if printer.extruder.can_extrude|lower == 'true' %}
    G1 E-{E} F2100
  {% else %}
    {action_respond_info("Extruder not hot enough")}
  {% endif %}
  {% if "xyz" in printer.toolhead.homed_axes %}
    G1 Z{z_safe} F900
    G90
    G1 X{x_park} Y{y_park} F6000
  {% else %}
    {action_respond_info("Printer not homed")}
  {% endif %} 

[gcode_macro RESUME]
description: Resume the actual running print
rename_existing: RESUME_BASE
gcode:
  ##### read E from pause macro #####
  {% set E = printer["gcode_macro PAUSE"].extrude|float %}
  #### get VELOCITY parameter if specified ####
  {% if 'VELOCITY' in params|upper %}
    {% set get_params = ('VELOCITY=' + params.VELOCITY)  %}
  {%else %}
    {% set get_params = "" %}
  {% endif %}
  ##### end of definitions #####
  {% if printer.extruder.can_extrude|lower == 'true' %}
    G91
    G1 E{E} F2100
  {% else %}
    {action_respond_info("Extruder not hot enough")}
  {% endif %}  
  RESUME_BASE {get_params}

[gcode_macro CANCEL_PRINT]
description: Cancel the actual running print
rename_existing: CANCEL_PRINT_BASE
gcode:
  TURN_OFF_HEATERS
  {% if "xyz" in printer.toolhead.homed_axes %}
    G91
    G1 Z4.5 F300
    G90
  {% else %}
    {action_respond_info("Printer not homed")}
  {% endif %}
    G28 X Y
  {% set y_park = printer.toolhead.axis_maximum.y|float - 5.0 %}
    G1 Y{y_park} F2000
    M84
  PUSH_PRINT_CANCEL
  CANCEL_PRINT_BASE
  
  
##### SHS 05/2024- Custom notifications config - https://github.com/leafeven/sonicpad #####
[gcode_pushover notify]
user: <snip>
token: <snip>
attach: http://localhost/webcam/?action=snapshot
verbose: True

[gcode_macro PUSH_TEST]
description: send test pushover message
gcode:
  SEND_PUSHOVER_MESSAGE CMD=notify TITLE="Test" MESSAGE="Im a teapot" PRIORITY=0

[gcode_macro PUSH_PRINT_START]
description: send pushover message, printing started
gcode:
  {% if printer.print_stats.filename %}
  {% set fname = printer.print_stats.filename %}
  {% endif %}
  SEND_PUSHOVER_MESSAGE CMD=notify TITLE="Print Started" MESSAGE="Printing Started: {fname}" PRIORITY=0

[gcode_macro PUSH_PRINT_STOP]
description: send pushover message, printing completed
gcode:
  {% if printer.print_stats.filename %}
  {% set fname = printer.print_stats.filename %}
  {% endif %}
  SEND_PUSHOVER_MESSAGE CMD=notify TITLE="Print Completed" MESSAGE="Printing Complete: {fname}" PRIORITY=0

[gcode_macro PUSH_PRINT_CANCEL]
description: send pushover message, printing canceled
gcode:
  {% if printer.print_stats.filename %}
  {% set fname = printer.print_stats.filename %}
  {% endif %}
  SEND_PUSHOVER_MESSAGE CMD=notify TITLE="Print Canceled" MESSAGE="Prining Canceled: {fname}" PRIORITY=1

[gcode_macro PUSH_PRINT_RUNOUT]
description: send pushover message, filament runout
gcode:
  {% if printer.print_stats.filename %}
  {% set fname = printer.print_stats.filename %}
  {% endif %}
  SEND_PUSHOVER_MESSAGE CMD=notify TITLE="Filament Out" MESSAGE="Filament Runout: {fname}" PRIORITY=1

##### END Custom notifications #####


[stepper_x]
step_pin: PC2
dir_pin: !PB9
enable_pin: !PC3
rotation_distance: 40
microsteps: 16
endstop_pin: !PA5
position_min: -5
position_endstop: 220
position_max: 220
homing_speed: 80

[stepper_y]
step_pin: PB8
dir_pin: !PB7
enable_pin: !PC3
rotation_distance: 40
microsteps: 16
endstop_pin: !PA6
position_min: -2
position_endstop: 220
position_max: 220
homing_speed: 80

[stepper_z]
step_pin: PB6
dir_pin: PB5
enable_pin: !PC3
rotation_distance: 8
microsteps: 16
endstop_pin: probe:z_virtual_endstop           #enable to use bltouch
#endstop_pin: !PA15                #disable to use bltouch
#position_endstop: -0.1
position_min: -10
position_max: 280
homing_speed: 4
second_homing_speed: 1
homing_retract_dist: 2.0

[extruder]
max_extrude_only_distance: 1000.0
step_pin: PB4
dir_pin: PB3
enable_pin: !PC3
rotation_distance: 7.5
microsteps: 16
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: PA1
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PC5
#control: pid
# tuned for stock hardware with 200 degree Celsius target
#pid_kp: 19.780
#pid_ki: 1.090
#pid_kd: 89.752
min_temp: 0
max_temp: 315

[heater_bed]
heater_pin: PA7
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PC4
#control: pid
# tuned for stock hardware with 50 degree Celsius target
#pid_kp: 60.061
#pid_ki: 0.400
#pid_kd: 2254.534
min_temp: 0
max_temp: 130

[idle_timeout]
timeout: 172800

[verify_heater extruder]
check_gain_time: 200
hysteresis: 5

[fan]
pin: PA0
kick_start_time: 0.5

#set heater fan runnig with temperature over 60;
[heater_fan my_nozzle_fan]
pin: PC0
max_power: 0.8
shutdown_speed : 0
heater:extruder
heater_temp : 60
fan_speed : 1.0

[mcu]
serial: /dev/serial/by-id/usb_serial_1
restart_method: command

# [mcu rpi]
# serial: /tmp/klipper_host_mcu

# [adxl345]
# cs_pin: rpi:None
# spi_speed: 2000000
# spi_bus: spidev2.0

# [resonance_tester]
# accel_chip: adxl345
# accel_per_hz: 70
# probe_points:
#      117.5,117.5,10


[input_shaper]
shaper_type_x = 2hump_ei
shaper_freq_x = 67.2
shaper_type_y = 2hump_ei
shaper_freq_y = 71.4


[filament_switch_sensor filament_sensor]
pause_on_runout: true
switch_pin: ^!PC15
runout_gcode: 
  {action_respond_info("RUNOUT: Filament runout")}
  NOTIFY_PRINT_RUNOUT
  PAUSE

[bltouch]
sensor_pin: ^PC14       #signal check port ^stand for pull up
control_pin: PC13       #singal control prot
x_offset: -7.0
y_offset: 10.0
#z_offset: 0          #z off_set configuration
speed: 20
stow_on_each_sample: false #high speed for bltoch,
samples: 1
#probe_with_touch_mode = true

[safe_z_home]
home_xy_position:125,95
speed: 200
z_hop: 10
z_hop_speed: 10

[bed_mesh]
speed: 150
mesh_min: 15, 15         #need to handle head distance with bl_touch
mesh_max: 195,195       #max probe range
probe_count: 5,5
fade_start: 1
fade_end: 10
fade_target: 0
algorithm: bicubic

[bed_screws]
screw1: 25, 33
screw2: 202, 33
screw3: 202, 202
screw4: 25, 202


[gcode_arcs]
#resolution: 1.0

[printer]
kinematics: cartesian
max_velocity: 300
max_accel: 5000
max_z_velocity: 10
max_z_accel: 1000
square_corner_velocity: 5.0

[exclude_object]

[include timelapse.cfg]
[include cx_gmcro.cfg]

#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [bltouch]
#*# z_offset = 1.600
#*#
#*# [bed_mesh default]
#*# version = 1
#*# points =
#*# 	0.305000, 0.220000, 0.137500, 0.080000, 0.000000
#*# 	0.217500, 0.120000, 0.030000, -0.012500, -0.065000
#*# 	0.090000, 0.017500, -0.045000, -0.077500, -0.140000
#*# 	0.027500, -0.062500, -0.122500, -0.160000, -0.172500
#*# 	0.042500, -0.060000, -0.127500, -0.167500, -0.177500
#*# x_count = 5
#*# y_count = 5
#*# mesh_x_pps = 2
#*# mesh_y_pps = 2
#*# algo = bicubic
#*# tension = 0.2
#*# min_x = 15.0
#*# max_x = 195.0
#*# min_y = 15.0
#*# max_y = 195.0
#*#
#*# [extruder]
#*# control = pid
#*# pid_kp = 26.365
#*# pid_ki = 1.890
#*# pid_kd = 91.949
#*#
#*# [heater_bed]
#*# control = pid
#*# pid_kp = 61.074
#*# pid_ki = 0.553
#*# pid_kd = 1685.652

```

**Comment by leafeven** [comment]
that config looks good, what do you have in your Slicer Machine Settings for Start and Stop g-code? it looks like you have a Ender 5 so I assume this part is similar to my Ender 3 S1

in cura my start g-code is 
`START_PRINT BED_TEMP={material_bed_temperature_layer_0} EXTRUDER_TEMP={material_print_temperature_layer_0}`

my stop gcode is
`END_PRINT`

IF you have these already watch your console when starting the printer to see what errors are thrown 

![image](https://github.com/leafeven/sonicpad/assets/18286441/e1510b62-47b2-4375-88d5-4720134036f6)

**Comment by JediMongoose** [comment]
I use Orcaslicer, so I edited the start/stop gcode sections and added START_PRINT, END_PRINT and voilla!  I'm now receiving notifications on print start/end. Thanks so much for your help!
